- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 9600 # Ganimed-RoleTime (160m)
  startingGear: SecurityCadetGear
  icon: "SecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance

- type: startingGear
  id: SecurityCadetGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSecGrey # Corvax-Resprite
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
  innerclothingskirt: ClothingUniformJumpskirtColorRed
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
