- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 25200 # Ganimed-RoleTime (420m)
    - !type:OverallPlaytimeRequirement
      time: 30000 # Ganimed-RoleTime (500m)
  startingGear: SecurityOfficerGear
  icon: "SecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetHelmet # Corvax-Resprite
    outerClothing: ClothingOuterVestArmorSec # Corvax-Resprite
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
