- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # Ganimed-RoleTime (900m)
  startingGear: WardenGear
  icon: "Warden"
  requireAdminNotify: true
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Armory
  - Maintenance
  - Service
  - Brig
  - External
  - Detective

- type: startingGear
  id: WardenGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
