- type: job
  id: TechnicalAssistant
  name: job-name-technical-assistant
  description: job-description-technical-assistant
  playTimeTracker: JobTechnicalAssistant
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 # Ganimed-RoleTime(120m)
  startingGear: TechnicalAssistantGear
  icon: "TechnicalAssistant"
  supervisors: job-supervisors-engineering
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: TechnicalAssistantGear
  equipment:
    head: ClothingHeadHatWelding
    jumpsuit: ClothingUniformJumpsuitColorYellow
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    id: TechnicalAssistantPDA
    belt: ClothingBeltUtilityFilled
    ears: ClothingHeadsetEngineering
  innerclothingskirt: ClothingUniformJumpskirtColorYellow
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
